### ISSUE TITLE
Migrating Articles fail with error "Not Found"

### ISSUE THREAD

**Issue by valdemarrolfsen** [theandrewykim/intercom-articles-importer#4]
We are trying to use the provided script to move articles from the US server to the EU server but we are experiencing some issues.

We have filled out the init.rb file with correct values as shown below:

```
EXPORT_ACCESS_TOKEN = "<US server token>"
IMPORT_ACCESS_TOKEN = "<EU server token>"
COLLECTION_NAME = "migration"
AUTHOR_ID = 5433925


#If you need to change URLS within your Articles that point to your old Helpcenter, fill in these fields. Otherwise, leave blank.
REPLACE_ARTICLE_URLS = false
EXPORT_CUSTOM_DOMAIN = "YOUR CUSTOM DOMAIN HERE"
IMPORT_CUSTOM_DOMAIN = "NEW CUSTOM DOMAIN HERE"

#commandthatexports-importsarticles
#List all articles that need to be published
#if needs to be copied -- create an ArticleIndex object. This will contain both the import_id AND the export_id



require 'intercom'
require 'nokogiri'
require 'mutations'
require 'pry'
require './fix_redirects.rb'
require './article.rb'
require './article_collection.rb'
require './article_importer.rb'


ExportWorkspace = Intercom::Client.new(token: EXPORT_ACCESS_TOKEN)
ImportWorkspace = Intercom::Client.new(token: IMPORT_ACCESS_TOKEN)
Collection = ImportWorkspace.collections.create(name: COLLECTION_NAME)
```

But when we run the script we get an error stating:

```
Failed to import article (Resource Not Found) ...moving on
Failed to import article (Resource Not Found) ...moving on
...
```

Any idea of what we are doing wrong?

**Comment by theandrewykim** [comment]
Hey @valdemarrolfsen  -- It looks like Intercom's API is returning a 404 for this. Any chance you could through a debugger in the script so we can find out what the ID you're querying here is?

**Comment by PhilipeLouchtch** [comment]
We're also migrating Intercom from US to EU. This script does not seem to be written for the across region migration use-case. Luckily, it's an easy fix. Just set the Intercom Client's base_url to the correct region.

In our case, the destination/import was EU, so in `script.rb` we changed line 29 to:

```ImportWorkspace = Intercom::Client.new(token: IMPORT_ACCESS_TOKEN, base_url: 'https://api.eu.intercom.io')```
